module.exports =
  meta_name        : ""
  meta_title       : ""
  meta_title_bt    : ""
  meta_description : ""
  meta_keywords    : ""
  meta_url         : ""
  meta_image       : ""
  fb_title         : ""
  fb_caption       : ""
  fb_description   : ""
  fb_link          : ""
  tw_url           : ""
  tw_text          : ""
  tw_hashtags      : ""
  line_text        : ""
  link_moony       : ""
  link_entry       : ""
  link_lesson      : ""
  link_prod        : ""
  video_id         : ""
  gaid             : "UA-XXXXXXXX-X"

